import type { ProposalDocumentSource } from './proposal-document.mapper';

/** A realistic Proposal as ProposalDocumentService loads it. Test-only. */
export function proposalDocumentSource(overrides: Partial<ProposalDocumentSource> = {}): ProposalDocumentSource {
  return {
    id: 'prop-1',
    proposalNumber: 'PRO-2026-00042',
    status: 'DRAFT',
    createdById: 'user-author',
    createdAt: new Date('2026-09-01T03:00:00.000Z'),
    area: 120,
    term: 60,
    startDate: new Date('2026-10-01T00:00:00.000+07:00'),
    rentPerSqm: 750000,
    camPerSqm: 90000,
    serviceFeeSqm: 0,
    businessSupportFeeSqm: 30000,
    rentCurrency: 'VND',
    escalationPercent: 5,
    deposit: 3,
    depositLease: null,
    depositFitout: 0,
    fitoutFee: 0,
    fitoutDays: 60,
    utilityFee: 0,
    operatingHours: null,
    afterHoursFee: 0,
    paymentTermDays: 30,
    handoverDate: new Date('2026-10-01T00:00:00.000+07:00'),
    openingDate: new Date('2026-12-01T00:00:00.000+07:00'),
    specialConditions: null,
    businessModel: 'SHOP',
    exchangeRate: null,
    exchangeRateSource: null,
    editorContent: null,
    unit: {
      id: 'unit-1',
      code: 'L3-E01',
      floor: { name: 'Level 3' },
      zone: { name: 'Zone E' },
      mall: { id: 'mall-hn', code: 'THISO-HN', name: 'THISO Mall Hà Nội', city: 'Hà Nội' },
    },
    tenant: null,
    lead: {
      company: 'CellphoneS JSC',
      brandName: 'CellphoneS',
      category: 'Technology',
      categoryRef: { id: 'cat-tech', code: 'TECH', name: 'Công nghệ' },
    },
    approvalWorkflow: null,
    creator: { id: 'user-author', fullName: 'Nguyễn Thị Lập', role: 'LEASING_EXECUTIVE', department: 'Leasing' },
    ...overrides,
  };
}
