import api from '@/lib/axios';
export const serviceContractsApi = {
  list: (params?: Record<string, unknown>) => api.get('/service-contracts', { params }).then(r => r.data),
  detail: (id: string) => api.get(`/service-contracts/${id}`).then(r => r.data),
  create: (data: Record<string, unknown>) => api.post('/service-contracts', data).then(r => r.data),
  updateStatus: (id: string, status: string) => api.patch(`/service-contracts/${id}/status`, { status }).then(r => r.data),
  upload: (id: string, file: File, documentType = 'CONTRACT', paymentId?: string) => { const form = new FormData(); form.append('file', file); form.append('documentType', documentType); if (paymentId) form.append('paymentId', paymentId); return api.post(`/service-contracts/${id}/documents`, form, { headers: { 'Content-Type': 'multipart/form-data' } }).then(r => r.data); },
  stats: () => api.get('/service-contracts/summary/stats').then(r => r.data),
  generateNumber: (mallCode?: string) => api.get('/service-contracts/tools/generate-number', { params: { mallCode } }).then(r => r.data),
  renew: (id: string, data: Record<string, unknown>) => api.post(`/service-contracts/${id}/renew`, data).then(r => r.data),
  createPayment: (id: string, data: Record<string, unknown>) => api.post(`/service-contracts/${id}/payments`, data).then(r => r.data),
  recurringPayments: (id: string, data: Record<string, unknown>) => api.post(`/service-contracts/${id}/payments/recurring`, data).then(r => r.data),
  updatePayment: (id: string, itemId: string, data: Record<string, unknown>) => api.patch(`/service-contracts/${id}/payments/${itemId}`, data).then(r => r.data),
  deletePayment: (id: string, itemId: string) => api.delete(`/service-contracts/${id}/payments/${itemId}`).then(r => r.data),
  createChecklist: (id: string, data: Record<string, unknown>) => api.post(`/service-contracts/${id}/checklist`, data).then(r => r.data),
  updateChecklist: (id: string, itemId: string, data: Record<string, unknown>) => api.patch(`/service-contracts/${id}/checklist/${itemId}`, data).then(r => r.data),
  deleteChecklist: (id: string, itemId: string) => api.delete(`/service-contracts/${id}/checklist/${itemId}`).then(r => r.data),
  createMilestone: (id: string, data: Record<string, unknown>) => api.post(`/service-contracts/${id}/milestones`, data).then(r => r.data),
  updateMilestone: (id: string, itemId: string, data: Record<string, unknown>) => api.patch(`/service-contracts/${id}/milestones/${itemId}`, data).then(r => r.data),
  deleteMilestone: (id: string, itemId: string) => api.delete(`/service-contracts/${id}/milestones/${itemId}`).then(r => r.data),
};
