CREATE TABLE "PatrolRoute" ("id" TEXT NOT NULL, "mallId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PatrolRoute_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PatrolPoint" ("id" TEXT NOT NULL, "routeId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "location" TEXT, "instructions" TEXT, "isRequired" BOOLEAN NOT NULL DEFAULT true, "order" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PatrolPoint_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PatrolShift" ("id" TEXT NOT NULL, "shiftNumber" TEXT NOT NULL, "mallId" TEXT NOT NULL, "routeId" TEXT NOT NULL, "assigneeId" TEXT, "createdById" TEXT NOT NULL, "scheduledAt" TIMESTAMP(3) NOT NULL, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'SCHEDULED', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PatrolShift_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PatrolCheck" ("id" TEXT NOT NULL, "shiftId" TEXT NOT NULL, "pointId" TEXT NOT NULL, "result" TEXT NOT NULL DEFAULT 'PENDING', "note" TEXT, "checkedAt" TIMESTAMP(3), "performedById" TEXT, "fileName" TEXT, "filePath" TEXT, "fileSize" INTEGER, "mimeType" TEXT, "workOrderId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PatrolCheck_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PatrolRoute_mallId_code_key" ON "PatrolRoute"("mallId", "code");
CREATE INDEX "PatrolRoute_mallId_isActive_idx" ON "PatrolRoute"("mallId", "isActive");
CREATE UNIQUE INDEX "PatrolPoint_routeId_code_key" ON "PatrolPoint"("routeId", "code");
CREATE INDEX "PatrolPoint_routeId_order_idx" ON "PatrolPoint"("routeId", "order");
CREATE UNIQUE INDEX "PatrolShift_shiftNumber_key" ON "PatrolShift"("shiftNumber");
CREATE INDEX "PatrolShift_mallId_status_scheduledAt_idx" ON "PatrolShift"("mallId", "status", "scheduledAt");
CREATE INDEX "PatrolShift_assigneeId_status_idx" ON "PatrolShift"("assigneeId", "status");
CREATE UNIQUE INDEX "PatrolCheck_shiftId_pointId_key" ON "PatrolCheck"("shiftId", "pointId");
CREATE INDEX "PatrolCheck_shiftId_result_idx" ON "PatrolCheck"("shiftId", "result");
CREATE INDEX "PatrolCheck_workOrderId_idx" ON "PatrolCheck"("workOrderId");
ALTER TABLE "PatrolRoute" ADD CONSTRAINT "PatrolRoute_mallId_fkey" FOREIGN KEY ("mallId") REFERENCES "Mall"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PatrolPoint" ADD CONSTRAINT "PatrolPoint_routeId_fkey" FOREIGN KEY ("routeId") REFERENCES "PatrolRoute"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PatrolShift" ADD CONSTRAINT "PatrolShift_mallId_fkey" FOREIGN KEY ("mallId") REFERENCES "Mall"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PatrolShift" ADD CONSTRAINT "PatrolShift_routeId_fkey" FOREIGN KEY ("routeId") REFERENCES "PatrolRoute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PatrolShift" ADD CONSTRAINT "PatrolShift_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PatrolShift" ADD CONSTRAINT "PatrolShift_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PatrolCheck" ADD CONSTRAINT "PatrolCheck_shiftId_fkey" FOREIGN KEY ("shiftId") REFERENCES "PatrolShift"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PatrolCheck" ADD CONSTRAINT "PatrolCheck_pointId_fkey" FOREIGN KEY ("pointId") REFERENCES "PatrolPoint"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PatrolCheck" ADD CONSTRAINT "PatrolCheck_performedById_fkey" FOREIGN KEY ("performedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
